src/Entity/Fuseau.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\IsFalse;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FuseauRepository")
 */
class Fuseau
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_fuseau;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $utc;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ville", mappedBy="fuseau")
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fuseau_pays;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pays_fr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $villes_fr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $villes_en;

    public function __construct()
    {
        $this->ville = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getNomFuseau(): ?string
    {
        return $this->nom_fuseau;
    }

    public function setNomFuseau(string $nom_fuseau): self
    {
        $this->nom_fuseau = $nom_fuseau;

        return $this;
    }

    public function getUtc(): ?string
    {
        return $this->utc;
    }

    public function setUtc(string $utc): self
    {
        $this->utc = $utc;

        return $this;
    }

    /**
     * @return Collection|Ville[]
     */
    public function getVille(): Collection
    {
        return $this->ville;
    }

    public function addVille(Ville $ville): self
    {
        if (!$this->ville->contains($ville)) {
            $this->ville[] = $ville;
            $ville->setFuseau($this);
        }

        return $this;
    }

    public function removeVille(Ville $ville): self
    {
        if ($this->ville->contains($ville)) {
            $this->ville->removeElement($ville);
            // set the owning side to null (unless already changed)
            if ($ville->getFuseau() === $this) {
                $ville->setFuseau(null);
            }
        }

        return $this;
    }

    public function getFuseauPays(): ?string
    {
        return $this->fuseau_pays;
    }

    public function setFuseauPays(?string $fuseau_pays): self
    {
        $this->fuseau_pays = $fuseau_pays;

        return $this;
    }

    public function getPaysFr(): ?string
    {
        return $this->pays_fr;
    }

    public function setPaysFr(?string $pays_fr): self
    {
        $this->pays_fr = $pays_fr;

        return $this;
    }

    public function __toString()
    {
      return $this->nom_fuseau;   // TODO: Implement __toString() method.
    }


    public function getFuseauHoraire(){
        date_default_timezone_set($this->nom_fuseau);
        $time = date("D, j F Y, H:i A");

        return $time;
    }

    public function getVillesFr(): ?string
    {
        return $this->villes_fr;
    }

    public function setVillesFr(?string $villes_fr): self
    {
        $this->villes_fr = $villes_fr;

        return $this;
    }

    public function getVillesEn(): ?string
    {
        return $this->villes_en;
    }

    public function setVillesEn(?string $villes_en): self
    {
        $this->villes_en = $villes_en;

        return $this;
    }
}

src/Entity/Pays.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PaysRepository")
 */
class Pays
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_fr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_en;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Continent", inversedBy="pays")
     * @ORM\JoinColumn(nullable=false)
     */
    private $continents;
    

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Fuseauhoraire", mappedBy="pays")
     */
    private $fuseauxhoraires;

    public function __construct()
    {
       
        $this->fuseauxhoraires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFr(): ?string
    {
        return $this->nom_fr;
    }

    public function setNomFr(string $nom_fr): self
    {
        $this->nom_fr = $nom_fr;

        return $this;
    }

    public function getNomEn(): ?string
    {
        return $this->nom_en;
    }

    public function setNomEn(string $nom_en): self
    {
        $this->nom_en = $nom_en;

        return $this;
    }


    public function getContinents(): ?Continent
    {
        return $this->continents;
    }

    public function setContinents(?Continent $continents): self
    {
        $this->continents = $continents;

        return $this;
    }


    /**
     * @return Collection|Fuseauhoraire[]
     */
    public function getfuseauxhoraires(): Collection
    {
        return $this->fuseauxhoraires;
    }

    public function addfuseauxhoraires(Fuseauhoraire $fuseauxhoraires): self
    {
        if (!$this->fuseauxhoraires->contains($fuseauxhoraires)) {
            $this->fuseauxhoraires[] = $fuseauxhoraires;
            $fuseauxhoraires->setPays($this);
        }

        return $this;
    }

    public function removefuseauxhoraires(Fuseauhoraire $fuseauxhoraires): self
    {
        if ($this->fuseauxhoraires->contains($fuseauxhoraires)) {
            $this->fuseauxhoraires->removeElement($fuseauxhoraires);
            // set the owning side to null (unless already changed)
            if ($fuseauxhoraires->getPays() === $this) {
                $fuseauxhoraires->setPays(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->fuseauxhoraires;
    }
}

src/Entity/Ville.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VilleRepository")
 */
class Ville
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville_fr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville_en;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Fuseauhoraire", inversedBy="villes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fuseaux;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVilleFr(): ?string
    {
        return $this->ville_fr;
    }

    public function setVilleFr(?string $ville_fr): self
    {
        $this->ville_fr = $ville_fr;

        return $this;
    }

    public function getVilleEn(): ?string
    {
        return $this->ville_en;
    }

    public function setVilleEn(?string $ville_en): self
    {
        $this->ville_en = $ville_en;

        return $this;
    }

    public function getFuseaux(): ?Fuseauhoraire
    {
        return $this->fuseaux;
    }

    public function setFuseaux(?Fuseauhoraire $fuseaux): self
    {
        $this->fuseaux = $fuseaux;

        return $this;
    }
}

templates/views/tables/datatables.html.twig
{% extends 'base.html.twig'%}

{% block body%}
	<div class="wrapper">
		<div class="main-header">
			<!-- Navbar Header -->
			<nav class="navbar navbar-header navbar-expand-lg" data-background-color="withe">
				<div class="col-md-6 float-right p-0" style="display: flex">
					<div class="col-md-1"><a class="button btn-primary btn-sm" href="{{ path('fuseau_fr') }}" style="text-decoration: none">Fr</a></div>
					<div class="col-md-1"><a class="button btn-danger btn-sm" href="{{ path('fuseau_en') }}" style="text-decoration: none">En</a></div>
				</div>

			</nav>

			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<h3 class="bg-white top-2" style="color: #ff8415;">Abidjan</h3>
						<h6 class="nav-item" id="clock" style="color: #ff8415;">Abidjan</h6>
					</div>
					<div class="col-md-3">
						<h3 class="bg-white top-2" style="color: #495aff;">Paris</h3>
						<h6 class="nav-item" id="clockA" style="color: #495aff;">Paris</h6>
					</div>
					<div class="col-md-3">
						<h3 class="bg-white top-2" style="color: #0c0cff;">New York</h3>
						<h6 class="nav-item" id="clockB" style="color: #150dff;">New York</h6>
					</div>
					<div class="col-md-3">
						<h3 class="bg-white top-2" style="color: #ff1524;">Shanghaï</h3>
						<h6 class="nav-item" id="clockC" style="color: #ff1524;">Shanghaï</h6>
					</div>
				</div>
			</div>
			<!-- End Navbar -->
		</div>
		<div class="container-fluid pt-5">
			<div class="content">
				<div class="page-inner">
					<div class="page-header">
						<h4 class="page-title"></h4>
						<h5 class="nav-item"></h5>
						<h5 class="nav-item"></h5>
					</div>
					<div class="row pt-3">
						<div class="col-md-12">
							<div class="card">

								<div class="card-header">
									<h4 class="card-title"></h4>
								</div>

								<script>
                                    {% if langue is defined and langue=='fr' %}
                                    moment.locale('fr');
                                    {% else %}
                                    moment.locale('en');
                                    {% endif %}
                                    const clock = document.getElementById('clock');
                                    function updateTime(){
                                        const now = moment();

                                        const hour = now.tz('Africa/Abidjan').format('HH:mm:ss A');
                                        const today = now.tz('Africa/Abidjan'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clock.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(updateTime, 1000);
                                    updateTime();

                                    const clockA = document.getElementById('clockA');
                                    function parisTime(){
                                        const now = moment();

                                        const hour = now.tz('Europe/Paris').format('HH:mm:ss A');
                                        const today = now.tz('Europe/Paris'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clockA.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(parisTime, 1000);
                                    parisTime();

                                    const clockB = document.getElementById('clockB');
                                    function uS(){
                                        const now = moment();

                                        const hour = now.tz('America/New_York').format('HH:mm:ss A');
                                        const today = now.tz('America/New_York'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clockB.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(uS, 1000);
                                    uS();

                                    const clockC = document.getElementById('clockC');
                                    function sH(){
                                        const now = moment();

                                        const hour = now.tz('Asia/Shanghai').format('HH:mm:ss A');
                                        const today = now.tz('Asia/Shanghai'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clockC.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(sH, 1000);
                                    sH();




								</script>
								<div class="card-body pt-5">
									<div class="table-responsive">
										<table id="basic-datatables" class="display table table-striped table-hover table-responsive" >
											<thead>
											<tr>
                                                <th class="hidden-caret">Continents</th>
												<th>UTC</th>
                                                {% if langue is defined and langue=='fr' %}
													<th>Pays</th>
													<th>Villes</th>
                                                {% else %}
													<th>Countries</th>
													<th>Cities</th>
                                                {% endif %}
												<!-- <th>Date</th>-->
												<th>Date</th>
											</tr>
											</thead>
											<tfoot>
											<tr>

												<th class="hidden">Continents</th>
												<th>UTC</th>
                                                {% if langue is defined and langue=='fr' %}
													<th>Pays</th>
													<th>Villes</th>
                                                {% else %}
													<th>Countries</th>
													<th>Cities</th>
                                                {% endif %}
												<!-- <th>Date</th>-->
												<th>Date</th>
											</tr>
											</tfoot>
											<tbody>
                                            {% for fuseau in fuseaux %}
												<tr>
                                                    {% if langue is defined and langue=='fr' %}
                                                        <td class="hidden">{{ fuseau.pays.continents.nomFr }}</td>
                                                        <td>{{ fuseau.utc }}</td>
														<td>{{ fuseau.pays.nomFr }}</td>
														<td>{{ fuseau.villeFr }}</td>
                                                    {% else %}
                                                        <td class="hidden">{{ fuseau.pays.continents.nomEn }}</td>
                                                        <td>{{ fuseau.utc }}</td>
														<td>{{ fuseau.pays.nomEn }}</td>
														<td>{{ fuseau.villeEn }}</td>
                                                    {% endif %}
													<!--<td> {{ fuseau.fuseauHoraire }} </td>-->
													<td id="clock{{ fuseau.id }}">111</td>

												</tr>
												<script>

                                                    const clock{{ fuseau.id }} = document.getElementById('clock{{ fuseau.id }}');
                                                    function sH{{ fuseau.id }}(){
                                                        const now = moment();

                                                        const hour = now.tz('{{ fuseau.fuseau }}').format('HH:mm:ss A');


                                                        const today = now.tz('{{ fuseau.fuseau }}'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                                        const  humanReadable =( today +" "+ hour);
                                                        clock{{ fuseau.id }}.textContent = humanReadable;

                                                        //console.log(humanReadable);
                                                    }
                                                    setInterval(sH{{ fuseau.id }}, 1000);
                                                    sH{{ fuseau.id }}();
												</script>


                                            {% endfor %}

											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<footer class="footer">
				<div class="container-fluid">
					<nav class="pull-left">
						<ul class="nav">
							<li class="nav-item">
								<a class="nav-link" href="#">

								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">

								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									Webversalis
								</a>
							</li>
						</ul>
					</nav>
					<div class="copyright ml-auto">
						2019 <i class="fa fa-heart heart text-danger"></i> by <a href="https://www.facebook.com/kpegowebmobile/">Kpego webmobile</a>
					</div>
				</div>
			</footer>
		</div>
	</div>

{% endblock %}

templates/views/tables/fuseau_index.html.twig
{% extends 'base.html.twig'%}

{% block body%}
    <div class="wrapper">
        <div class="main-header">
            <!-- Navbar Header -->
            <nav class="navbar navbar-header navbar-expand-lg" data-background-color="withe">
                <div class="col-md-6 float-right p-0" style="display: flex">
                    <div class="col-md-1"><a class="button btn-primary btn-sm" href="{{ path('fuseau_fr') }}" style="text-decoration: none">Fr</a></div>
                    <div class="col-md-1"><a class="button btn-danger btn-sm" href="{{ path('fuseau_en') }}" style="text-decoration: none">En</a></div>
                </div>

            </nav>

            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <h3 class="bg-white top-2" style="color: #ff8415;">Abidjan</h3>
                        <h6 class="nav-item" id="clock" style="color: #ff8415;">Abidjan</h6>
                    </div>
                    <div class="col-md-3">
                        <h3 class="bg-white top-2" style="color: #495aff;">Paris</h3>
                        <h6 class="nav-item" id="clockA" style="color: #495aff;">Paris</h6>
                    </div>
                    <div class="col-md-3">
                        <h3 class="bg-white top-2" style="color: #0c0cff;">New York</h3>
                        <h6 class="nav-item" id="clockB" style="color: #150dff;">New York</h6>
                    </div>
                    <div class="col-md-3">
                        <h3 class="bg-white top-2" style="color: #ff1524;">Shanghaï</h3>
                        <h6 class="nav-item" id="clockC" style="color: #ff1524;">Shanghaï</h6>
                    </div>
                </div>
            </div>
            <!-- End Navbar -->
        </div>
        <div class="container-fluid pt-5">
            <div class="content">
                <div class="page-inner">
                    <div class="page-header">
                        <h4 class="page-title"></h4>
                        <h5 class="nav-item"></h5>
                        <h5 class="nav-item"></h5>
                    </div>
                    <div class="row pt-3">
                        <div class="col-md-12">
                            <div class="card">

                                <div class="card-header">
                                    <h4 class="card-title"></h4>
                                </div>

                                <script>
                                    {% if langue is defined and langue=='fr' %}
                                    moment.locale('fr');
                                    {% else %}
                                    moment.locale('en');
                                    {% endif %}
                                    const clock = document.getElementById('clock');
                                    function updateTime(){
                                        const now = moment();

                                        const hour = now.tz('Africa/Abidjan').format('HH:mm:ss A');
                                        const today = now.tz('Africa/Abidjan'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clock.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(updateTime, 1000);
                                    updateTime();

                                    const clockA = document.getElementById('clockA');
                                    function parisTime(){
                                        const now = moment();

                                        const hour = now.tz('Europe/Paris').format('HH:mm:ss A');
                                        const today = now.tz('Europe/Paris'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clockA.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(parisTime, 1000);
                                    parisTime();

                                    const clockB = document.getElementById('clockB');
                                    function uS(){
                                        const now = moment();

                                        const hour = now.tz('America/New_York').format('HH:mm:ss A');
                                        const today = now.tz('America/New_York'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clockB.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(uS, 1000);
                                    uS();

                                    const clockC = document.getElementById('clockC');
                                    function sH(){
                                        const now = moment();

                                        const hour = now.tz('Asia/Shanghai').format('HH:mm:ss A');
                                        const today = now.tz('Asia/Shanghai'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                        const  humanReadable =(hour);
                                        clockC.textContent = humanReadable;

                                        console.log(humanReadable);
                                    }
                                    setInterval(sH, 1000);
                                    sH();




                                </script>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table id="basic-datatables" class="display table table-striped table-hover table-responsive" >
                                            <thead>
                                            <tr>
                                                <th>UTC</th>
                                                {% if langue is defined and langue=='fr' %}
                                                    <th>Pays</th>
                                                    <th>Villes</th>
                                                {% else %}
                                                    <th>Countries</th>
                                                    <th>Cities</th>
                                                {% endif %}
                                                <!-- <th>Date</th>-->
                                                <th>Date</th>
                                            </tr>
                                            </thead>
                                            <tfoot>
                                            <tr>

                                                <th>UTC</th>
                                                {% if langue is defined and langue=='fr' %}
                                                    <th>Pays</th>
                                                    <th>Villes</th>
                                                {% else %}
                                                    <th>Countries</th>
                                                    <th>Cities</th>
                                                {% endif %}
                                                <!-- <th>Date</th>-->
                                                <th>Date</th>
                                            </tr>
                                            </tfoot>
                                            <tbody>
                                            {% for fuseau in fuseaux %}
                                                <tr>
                                                    <td>{{ fuseau.utc }}</td>
                                                    {% if langue is defined and langue=='fr' %}
                                                        <td>{{ fuseau.pays.nomFr }}</td>
                                                        <td>{{ fuseau.villeFr }}</td>
                                                    {% else %}
                                                        <td>{{ fuseau.pays.nomEn }}</td>
                                                        <td>{{ fuseau.villeEn }}</td>
                                                    {% endif %}
                                                    <!--<td> {{ fuseau.fuseauHoraire }} </td>-->
                                                    <td id="clock{{ fuseau.id }}">111</td>

                                                </tr>
                                                <script>

                                                    const clock{{ fuseau.id }} = document.getElementById('clock{{ fuseau.id }}');
                                                    function sH{{ fuseau.id }}(){
                                                        const now = moment();

                                                        const hour = now.tz('{{ fuseau.fuseau }}').format('HH:mm:ss A');


                                                        const today = now.tz('{{ fuseau.fuseau }}'){% if langue is defined and langue=='fr' %}.format('dddd  Do MMMM  YYYY');{% else %}.format('dddd MMMM Do YYYY');{% endif %}

                                                        const  humanReadable =( today +" "+ hour);
                                                        clock{{ fuseau.id }}.textContent = humanReadable;

                                                        //console.log(humanReadable);
                                                    }
                                                    setInterval(sH{{ fuseau.id }}, 1000);
                                                    sH{{ fuseau.id }}();
                                                </script>


                                            {% endfor %}

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#">

                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">

                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    Webversalis
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright ml-auto">
                        2019 <i class="fa fa-heart heart text-danger"></i> by <a href="https://www.facebook.com/kpegowebmobile/">Kpego webmobile</a>
                    </div>
                </div>
            </footer>
        </div>
    </div>

{% endblock %}

templates/views/tables/test.html.twig
{% for fuseau in fuseaux %}

    <pre>
        {{ fuseau.id }}
        {{ fuseau.pays.continents.nomFr }}
        {{ fuseau.pays.nomFr }}
        {{ fuseau.villeFr }}
        {{ fuseau.fuseau }}
    </pre>


{% endfor %}