src/Entity/Fuseau.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\IsFalse;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FuseauRepository")
 */
class Fuseau
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_fuseau;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $utc;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ville", mappedBy="fuseau")
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fuseau_pays;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pays_fr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $villes_fr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $villes_en;

    public function __construct()
    {
        $this->ville = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getNomFuseau(): ?string
    {
        return $this->nom_fuseau;
    }

    public function setNomFuseau(string $nom_fuseau): self
    {
        $this->nom_fuseau = $nom_fuseau;

        return $this;
    }

    public function getUtc(): ?string
    {
        return $this->utc;
    }

    public function setUtc(string $utc): self
    {
        $this->utc = $utc;

        return $this;
    }

    /**
     * @return Collection|Ville[]
     */
    public function getVille(): Collection
    {
        return $this->ville;
    }

    public function addVille(Ville $ville): self
    {
        if (!$this->ville->contains($ville)) {
            $this->ville[] = $ville;
            $ville->setFuseau($this);
        }

        return $this;
    }

    public function removeVille(Ville $ville): self
    {
        if ($this->ville->contains($ville)) {
            $this->ville->removeElement($ville);
            // set the owning side to null (unless already changed)
            if ($ville->getFuseau() === $this) {
                $ville->setFuseau(null);
            }
        }

        return $this;
    }

    public function getFuseauPays(): ?string
    {
        return $this->fuseau_pays;
    }

    public function setFuseauPays(?string $fuseau_pays): self
    {
        $this->fuseau_pays = $fuseau_pays;

        return $this;
    }

    public function getPaysFr(): ?string
    {
        return $this->pays_fr;
    }

    public function setPaysFr(?string $pays_fr): self
    {
        $this->pays_fr = $pays_fr;

        return $this;
    }

    public function __toString()
    {
      return $this->nom_fuseau;   // TODO: Implement __toString() method.
    }


    public function getFuseauHoraire(){
        date_default_timezone_set($this->nom_fuseau);
        $time = date("D, j F Y, H:i A");

        return $time;
    }

    public function getVillesFr(): ?string
    {
        return $this->villes_fr;
    }

    public function setVillesFr(?string $villes_fr): self
    {
        $this->villes_fr = $villes_fr;

        return $this;
    }

    public function getVillesEn(): ?string
    {
        return $this->villes_en;
    }

    public function setVillesEn(?string $villes_en): self
    {
        $this->villes_en = $villes_en;

        return $this;
    }
}

src/Form/FuseauType.php
<?php

namespace App\Form;

use App\Entity\Fuseau;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FuseauType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_fuseau')
            ->add('utc')
            ->add('fuseau_pays')
            ->add('pays_fr')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Fuseau::class,
        ]);
    }
}

src/Controller/FuseauController.php
<?php

namespace App\Controller;

use App\Entity\Fuseau;
use App\Form\FuseauType;
use App\Repository\FuseauRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/fuseau")
 */
class FuseauController extends AbstractController
{
    /**
     * @Route("/", name="fuseau_index", methods={"GET"})
     */
    public function index(FuseauRepository $fuseauRepository): Response
    {

            date_default_timezone_set('Pacific/Pago_Pago');

            $data = date("D, j F Y, H:i A");
        return $this->render('views/tables/datatables.html.twig', [
            'fuseaus' => $fuseauRepository->findAll(),
            'data' => $data
        ]);
    }

    /**
     * @Route("/new", name="fuseau_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $fuseau = new Fuseau();
        $form = $this->createForm(FuseauType::class, $fuseau);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($fuseau);
            $entityManager->flush();

            return $this->redirectToRoute('fuseau_index');
        }

        return $this->render('fuseau/new.html.twig', [
            'fuseau' => $fuseau,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fuseau_show", methods={"GET"})
     */
    public function show(Fuseau $fuseau): Response
    {

        return $this->render('fuseau/show.html.twig', [
            'fuseau' => $fuseau,

        ]);
    }

    /**
     * @Route("/{id}/edit", name="fuseau_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Fuseau $fuseau): Response
    {
        $form = $this->createForm(FuseauType::class, $fuseau);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('fuseau_index');
        }

        return $this->render('fuseau/edit.html.twig', [
            'fuseau' => $fuseau,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fuseau_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Fuseau $fuseau): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fuseau->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($fuseau);
            $entityManager->flush();
        }

        return $this->redirectToRoute('fuseau_index');
    }
}

templates/fuseau/_delete_form.html.twig
<form method="post" action="{{ path('fuseau_delete', {'id': fuseau.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fuseau.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fuseau/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fuseau/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fuseau{% endblock %}

{% block body %}
    <h1>Edit Fuseau</h1>

    {{ include('fuseau/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('fuseau_index') }}">back to list</a>

    {{ include('fuseau/_delete_form.html.twig') }}
{% endblock %}

templates/fuseau/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fuseau index{% endblock %}

{% block body %}
    <h1>Fuseau index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_fuseau</th>
                <th>Utc</th>
                <th>Fuseau_pays</th>
                <th>Pays_fr</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fuseau in fuseaus %}
            <tr>
                <td>{{ fuseau.id }}</td>
                <td>{{ fuseau.nomFuseau }}</td>
                <td>{{ fuseau.utc }}</td>
                <td>{{ fuseau.fuseauPays }}</td>
                <td>{{ fuseau.paysFr }}</td>
                <td>
                    <a href="{{ path('fuseau_show', {'id': fuseau.id}) }}">show</a>
                    <a href="{{ path('fuseau_edit', {'id': fuseau.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('fuseau_new') }}">Create new</a>
{% endblock %}

templates/fuseau/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fuseau{% endblock %}

{% block body %}
    <h1>Create new Fuseau</h1>

    {{ include('fuseau/_form.html.twig') }}

    <a href="{{ path('fuseau_index') }}">back to list</a>
{% endblock %}

templates/fuseau/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fuseau{% endblock %}

{% block body %}
    <h1>Fuseau</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fuseau.id }}</td>
            </tr>
            <tr>
                <th>Nom_fuseau</th>
                <td>{{ fuseau.nomFuseau }}</td>
            </tr>
            <tr>
                <th>Utc</th>
                <td>{{ fuseau.utc }}</td>
            </tr>
            <tr>
                <th>Fuseau_pays</th>
                <td>{{ fuseau.fuseauPays }}</td>
            </tr>
            <tr>
                <th>Pays_fr</th>
                <td>{{ fuseau.paysFr }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('fuseau_index') }}">back to list</a>

    <a href="{{ path('fuseau_edit', {'id': fuseau.id}) }}">edit</a>

    {{ include('fuseau/_delete_form.html.twig') }}
{% endblock %}